# This is the main config. Parameters are updated and possibly overwritten by dataset dependent configs.
model:
  mode: train # "train", "test", "predict", "predict_features"
  batch_size: 8
  epochs: 20
  learning_rate: 0.1
  optimizer: sgd
  class_weighted_loss: True
  loss_function: categorical_crossentropy # "categorical_crossentropy", "focal_loss"
  metrics_patch_level: True
  metrics_wsi_level: True
  metrics_for_monitoring: val_f1_mean
  load_model: None # 'None' or path to experiment folder which containes 'models' directory with .h5 files
  save_model: False # True or False
  feature_extractor:
    type: efficientnetb5 # "fsconv", "simple_cnn", "mobilenetv2", "resnet50", "efficientnetb0", "efficientnetb1", "eff.."
    global_max_pooling: False
    num_output_features: 8 # feature dimension of feature extractor output, set to 0 to skip this layer
    output_activation: sigmoid # sigmoid, relu
  head:
    type: gp # deterministic, gp, bnn
    deterministic:
      dropout: 0.2
      number_hidden_units: 0 # feature dimension of hidden layer, set to 0 to skip this layer
    gp:
      inducing_points: 200
      kl_weights: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0]
    bnn:
      number_hidden_units: 100
      kl_loss_factor: 1

data:
  dataset_config: ./dataset_dependent/panda/config.yaml
  supervision: active_learning # 'supervised', 'active_learning'
  random_seed: 1
  augmentation:
    brightness_range: [0.5, 1.5] # brightness augmentation range for strong augmentation
    channel_shift: 0.0
  active_learning:
    start:
      wsis_per_class: 1
      labels_per_class_and_wsi: 10
    acquisition:
      strategy: 'max_var'
      wsis: 5
      labels_per_wsi: 10
      after_epochs_of_no_improvement: 10
      total_steps: 20

logging:
  log_artifacts: False
  interval: 5
  test_on_the_fly: True
  run_name: efficientnetb1
  tracking_url: /home/arne/projects/mlruns