data:
  dataset_name: panda
  dir: /home/arne/data/Panda/Panda_patches_center/
  data_split_dir: /home/arne/data/Panda/Panda_patches_center/
  artifact_dir: ./dataset_dependent/panda/
  image_target_size: [512, 512]
  num_classes: 4
  dataset_type: prostate_cancer