data:
  dataset_name: panda
  dir: /data/BasesDeDatos/Panda/Panda_patches_act/
  data_split_dir: /data/BasesDeDatos/Panda/Panda_patches_act/
  artifact_dir: ./dataset_dependent/panda/
  image_target_size: [512, 512]
  num_classes: 4
  dataset_type: prostate_cancer